all: Epam_javaCourse_AGoldyrev_design_public_printer.pdf

Epam_javaCourse_AGoldyrev_design_public_printer.pdf: Epam_javaCourse_AGoldyrev_design_public_printer.docx
	pandoc $^ --output=$@

clean:
	rm -f Epam_javaCourse_AGoldyrev_design_public_printer.pdf
